### ISSUE TITLE
Can I capture UserMedia stream and do processing on that along with using SpeechRecognition

### ISSUE THREAD

**Issue by dhruvjaglan** [WICG/speech-api#101]
I am trying to use a custom pause detection and record audio, along with web speech API's SpeechRecognition.

But as soon as I try to use MediaStream, SpeechRecognition keeps disconnecting automatically on Android chrome. It works fine on Mac Chrome.

Is there a solution for the same?

**Comment by foolip** [comment]
@dhruvjaglan if there's something that works on Chrome for macOS but not on Android, that sounds like a Chrome bug. Can you file a bug at https://bugs.chromium.org/p/chromium/issues/entry instead?
