### ISSUE TITLE
Bubbling model for SpeechSynthesisUtterance

### ISSUE THREAD

**Issue by dontcallmedom** [WICG/speech-api#103]
The spec states that
> [SpeechSynthesisUtterance Events]  bubble up to SpeechSynthesis
https://wicg.github.io/speech-api/#utterance-events

Is that actually implemented anywhere? if so, the spec should describe the [get the parent](https://dom.spec.whatwg.org/#get-the-parent) relationship between utterances on the parent `SpeechSynthesis`, and the relevant `on…` event handlers should be added to the `SpeechSynthesis` interface.

If not, the spec should remove that mention.

**Comment by foolip** [comment]
From quick testing in Chromium, the "start" event at least does *not* bubble, and additionally `event.composedPath()` is the empty array, so there must be no "get the parent" implementation for `SpeechSynthesisUtterance`.
