### ISSUE TITLE
Speach Destination

### ISSUE THREAD

**Issue by St3ph3nBr00ks** [WICG/speech-api#106]
This API works well in testing but the web calls are being blocked when the app I am developing with it is run behind a VPN. Is the destination speech is sent to "speech.platform.bing.com" using UDP? Platform is Microsoft Edge Browser on Windows 10.

**Comment by marcoscaceres** [comment]
Hi @St3ph3nBr00ks! This repo is for spec issues, not for implementation specific issues. Unfortunately, I don't think we will be of much help. 

closing as out of scope.
