### ISSUE TITLE
Use FrozenArray<SpeechRecognitionResult> and remove SpeechRecognitionResultList

### ISSUE THREAD

**Issue by saschanaz** [WICG/speech-api#12]
Related 2013 discussion: https://lists.w3.org/Archives/Public/public-speech-api/2013Feb/0011.html

There was a previous attempt to remove SpeechRecognitionResultList but was reverted because [Web IDL forbids attributes to return sequences](https://heycam.github.io/webidl/#idl-attributes).

>The type of the attribute, after resolving typedefs, must not be a nullable or non-nullable version of any of the following types:
>* a sequence type
>* a dictionary type
>* a record type
>* a union type that has a nullable or non-nullable sequence type, dictionary, or record as one of its flattened member types

Attributes still can use FrozenArray [which is also represented by JS native array object](https://heycam.github.io/webidl/#es-frozen-array).

**Comment by foolip** [comment]
The compat risk here is the `item` method, which a plain Array doesn't have. Content in the wild might be using it, but if multiple implementers would like to simplify this, then we could add a use counter in Chrome and see if there's much usage.

**Comment by foolip** [comment]
See also https://www.w3.org/Bugs/Public/show_bug.cgi?id=30010.

**Comment by foolip** [comment]
Since `SpeechRecognitionResultList` has now shipped in Safari 14.1, I think we should not change this, it's just not worth it.
