### ISSUE TITLE
Transfer to WICG

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/speech-api#67]
@siusin could you please transfer this repository for us to the WICG based on:
https://lists.w3.org/Archives/Public/public-speech-api/2019Oct/0001.html

I'll send a PR the w3c.github.io repo so links don't break.

**Comment by marcoscaceres** [comment]
Redirect: https://github.com/w3c/w3c.github.io/pull/72

**Comment by guest271314** [comment]
@marcoscaceres Have been active in this repository before attempting to contribute to repositories under the WICG umbrella. Your decision to indefinitely ban this user from WICG umbrella repositories will certainly affect this proposed change. Your imposed ban from WICG should not be retroactively applied to this account should speech-api be moved to WICG. Meaning, should still be able to contribute to this repository in spite of your imposed indeterminate WICG ban.

**Comment by marcoscaceres** [comment]
If you agree to play by the rules, then I don’t see any reason not to lift the ban. You will need to join the WICG, abide by our code of conduct, and make the prerequisite IPR commitments tho.

**Comment by guest271314** [comment]
@marcoscaceres As long as your parent organization fixes its current deliberate obfuscation practice re what they are actually asking for, can sign up to become a "member". Again, using the term "IPR" when the acronynm is not defined _anywhere_ in W3C policy documents - even after being told _exactly_ what to change the unknown term "IPR" _after asking for the guidance_ cannot currently be described as anything other than deliberate deception.

**Comment by marcoscaceres** [comment]
I think it’s fair to know what you are signing. If I put you in touch with a W3C lawyer, would the help?

**Comment by guest271314** [comment]
The lawyer already told the individual in charge of the repository what to do. There is no need for behind closed-door contact. Either individuals are being lazy re all of the documents that would need to be changed (let it be, hiding in plain sight) or intentionally deceiving people.  The change is not _only_ for this user, but for transparency, to avoid the issues at SE (https://judaism.meta.stackexchange.com/questions/5193/stack-overflow-inc-sinat-chinam-and-the-goat-for-azazel; https://meta.stackoverflow.com/a/389908) that warned the Mod Squad over there about each time they banned this user. Now they perhaps understand. Invested over 4 years into litigating in federal ct. over a single word (statutory construction). Cannot simply ignore the glaring issue of an organization that knows better using an acronym that currently has absolutely no citable defintion.

**Comment by guest271314** [comment]
Again, own a trademark and filed for a patent. So have been through the intellectual property process entirely, from concept to post-examination. An undefined acronym in a patent application will not be missed by any examiner.

**Comment by marcoscaceres** [comment]
ok, but have you stopped to reflect that somehow Google, Apple, Microsoft, Mozilla, and countless other companies’ lawyers were ok to sign this agreement yet somehow you’ve found some profound conspiratorial deception with it? 🧐 

Anyway, ball is in your court. You are clearly capable, smart, and articulate so hopefully you will reconsider your position so you can continue to participate.

**Comment by marcoscaceres** [comment]
(Also the fact that you’ve filed for a patent is precisely the reason for you to sign the agreement)

**Comment by guest271314** [comment]
> ok, but have you stopped to reflect that somehow Google, Apple, Microsoft, Mozilla, and countless other companies’ lawyers were ok to sign this agreement yet somehow you’ve found some profound conspiratorial deception with it?

Yes. That does not change the facts. That only means those organizations have signed on to a document where a specific acronym has no meaning defined by the organization proferring the adhesion contract. 

There are other examples in the wild of such behaviour. The term "race" is not defined by any Public Law enacted by U.S. Congress, yet the U.S. Census Bureau and other documents generated by _administrative agencies_ ask people what "race" they self-identify with (per U.S. O.M.B. Directive 15) - yet AFAICT there is no statue backing the adminsitrative regulations re "race". As yet, no official that have posed the question to has been able to cite _any law_ where the term "race" is defined by _law_.  That does not even reach the individual definitions of the five "race" political classifications proferred by the _administrative regulations_. 

> The concept of race has no genetic or scientific basis. - Criag Vinter https://www.nationalgeographic.com/magazine/2018/04/race-genetics-science-africa/

> The "racial" worldview was invented to assign some groups to perpetual low status, while others were permitted access to privilege, power, and wealth. - American Association of Anthropologists https://www.americananthro.org/ConnectWithAAA/Content.aspx?ItemNumber=2583

Just because the companies cited ignore the glaring omission does not mean anything. At least some of those companies have participated in programs to provide user data to other undisclosed parties (linking to Wikipedia here for expediency, not as a primary resource), making the assertion that simply because a company is big and perform an action that everyone else should as well fall in the face of reason and logic. What you are essentially suggesting is that since "all the cool kids are doing it" an individual should just follw the pied piper.

What is revealing is that you recognize the problem yet are not equally steadfast in demanding the problem be immediately correct compared to "just sign".

**Comment by guest271314** [comment]
Invested four years on researching the p terms "race", "black" and "white" alone. To the point where there is nowhere to go for any individual or institution which uses those terms - and are actually asked questions about the origin and defintiion of those terms. Have not yet encountered any individual who self-identifies as "white" or "black" who have been able to cite the controlling defintion they are relying on for those terms. That should give you pause re citing some corporations as an example of what they have performed, or an inverse examinations, failed to perform re their due diligence. 

Words - and undefined acronyms - are important.

**Comment by guest271314** [comment]
To illustrate how ignorance - and indeed a fraud - can persist for hundreds of years when not challenged directly 

> There is no theory (in any discipline) of the number of black racial groups in Africa - https://law.meta.stackexchange.com/questions/701/explain-the-reasoning-behind-voting-to-place-this-question-on-hold/702#702

The law in 1664

> Proceedings and Acts of the General Assembly January 1637/8-September 1664 (Volume 1, Page 533-534) Liber W H&L (Maryland; 1664)
> 
> An Act Concerning Negroes & other Slaues
> 
> ...And forasmuch as divers freeborne English women...

The repealed and re-enacted law in 1681 - the first usage of the term "White" relevant to politically classifying a natural person that have been able to find in Colonial law

> Proceedings and Acts of the General Assembly, October 1678-November 1683 (Volume 7, Page 203-205) Liber W. H. (Marlyland; 1681)
> 
> An Act concerning Negroes & Slaves—
> 
> ...And for as much a diuerse ffreeborne Englishe or White- woman...

That insertion of "White-" is an invention of a legal fiction that persists 338 years later.

**Comment by foolip** [comment]
I'd like to request that the move doesn't happen until we've allowed for some time to react to this internally at Google, while I expressed support on the list there are other stakeholders. Please give us a week or so.

**Comment by foolip** [comment]
@guest271314 you are getting very far off topic now and I'm going to delete some of your comments. Please take @marcoscaceres's advice and talk to a W3C lawyer if you have concerns about joining the WICG.

**Comment by guest271314** [comment]
@foolip Ok. Fair enough. Same user name at gmail. You and they have permission to make contact there. That "IPR" still needs to be changed to exactly what it means.

**Comment by guest271314** [comment]
@marcoscaceres 

> I think it’s fair to know what you are signing. If I put you in touch with a W3C lawyer, would the help?

Perhaps that will help. Will give it a try anyway. The point of fact is not about this user. It is about transparency in general. See above comment. Have them contact by email or whatever means they decide, public or private; the facts will not change.

**Comment by guest271314** [comment]
FWIW Found the relevant language in an W3C document. Filed [PR](https://github.com/w3c/ash-nazg/pull/162) for reference and clarity. Joined W3C. Joined WICG.

**Comment by marcoscaceres** [comment]
Ok, but it looks like you joined without providing a legal name? Is that the case?

**Comment by guest271314** [comment]
@marcoscaceres Not sure what you mean? Found at least one W3C document which expliticly defined "IPR" internally. Created a valid W3C account. Created a valid WICG account ("joined"). 

Do we now need to parse what "legal name" means, and evaluate historical and contemporary examples of what a "legal name" is?

**Comment by foolip** [comment]
@guest271314 no, please do not go down another rabbit hole on this thread. Whatever the requirements for joining the WICG are, please work them out off-thread.

**Comment by siusin** [comment]
@marcoscaceres @foolip sure, please let us know when it's ready to be transferred
(Cc @sideshowbarker as he has the owner access to both GitHub orgs).

**Comment by marcoscaceres** [comment]
Thanks @siusin. We'll wait for @foolip to give us a 👍.

**Comment by foolip** [comment]
We've discussed internally now and don't have any objection to transferring this to the WICG.

We'll continue to keep an eye on the repo/spec going forward as well, and given the [pull request template](https://github.com/w3c/speech-api/pull/64) I have high confidence that changes which wouldn't work at all for Chromium would surface quickly.

**Comment by sideshowbarker** [comment]
done
